// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4fp-u4rzTiO7t3FN8INCIwi-dTuH_1g',
    appId: '1:799465605934:web:5581893a4668a7ec4688bf',
    messagingSenderId: '799465605934',
    projectId: 'cleanify-cb768',
    authDomain: 'cleanify-cb768.firebaseapp.com',
    storageBucket: 'cleanify-cb768.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoxFiHw6yMYJFru6KAnfb3__4yGeWM4EM',
    appId: '1:799465605934:android:0972c1fb658664d34688bf',
    messagingSenderId: '799465605934',
    projectId: 'cleanify-cb768',
    storageBucket: 'cleanify-cb768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRC25652aQpY_B4a_d5DixoIYHF03286U',
    appId: '1:799465605934:ios:07abfe5dd3cc87b84688bf',
    messagingSenderId: '799465605934',
    projectId: 'cleanify-cb768',
    storageBucket: 'cleanify-cb768.appspot.com',
    iosBundleId: 'com.example.cleanify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRC25652aQpY_B4a_d5DixoIYHF03286U',
    appId: '1:799465605934:ios:dd72bce1252859fd4688bf',
    messagingSenderId: '799465605934',
    projectId: 'cleanify-cb768',
    storageBucket: 'cleanify-cb768.appspot.com',
    iosBundleId: 'com.example.cleanify.RunnerTests',
  );
}
